title: "Intertidal Curriculum Pilot"
navbar:
  right:
    - text: "Home"
      href: index.qmd
    - text: "Schedule"
      href: schedule.qmd
    - text: "Lessons"
      menu:
        - text: "Intertidal Lessons"
          href: lessons/intertidal_lesson1.qmd
        - text: "Art Lessons"
          href: lessons/art_lesson1.qmd
    - text: "Community Builders"
      href: community_builders.qmd
    - text: "Resources"
      href: resources.qmd
