project:
  type: website
  output-dir: docs

website:
  title: "Intertidal Innovators"
  navbar:
    right:
      - text: "2024 Pilot"
        href: pilot.qmd
      - text: "Schedule"
        href: schedule.qmd
      
      - text: "Lessons"
        menu:
          - text: "Learning Objectives"
            href: learningobjectives.qmd
          - text: "Culturally Responsive Learning"
            href: 6_crt_lessons_formatted.qmd
          - text: "Intertidal & Art Lessons"
            href: IA_commbuild.qmd
          - text: "Advanced Intertidal Lessons"
            href: advanced_content.qmd
      - text: "Resources"
        menu:
          - text: 5E's 
            href: 5e_explainer.qmd
          - text: Open Source Resources
            href: resources.qmd
      - icon: github
        href: https://github.com/ChrisMantegna
      - icon: twitter
        href: https://twitter.com/MarineMantegna
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: source
