project:
  type: website
  output-dir: docs

website:
  title: "Intertidal Innovators"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: 2024 Pilot
      - href: pilot.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Community Builders"
        href: community_builders.qmd
      - text: "Lessons"
        menu:
          - text: "Culturally Responsive Learning"
            href: crt_lessons.qmd
          - text: "Intertidal Lessons"
            href: lessons/intertidal_lesson1.qmd
          - text: "Advanced Intertidal Lessons"
            href: advanced_content.qmd
          - text: "Digital Art Lessons"
            href: lessons/art_lesson1.qmd
    
      - text: "Resources"
        menu:
          - text: 5E's 
            href: 5e_explainer.qmd
          - text: Open Source Resources
        href: resources.qmd
      - icon: github
        href: https://github.com/ChrisMantegna
      - icon: twitter
        href: https://twitter.com/MarineMantegna
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: source
