---
title: "Welcome to the Intertidal"
format: html
layout: default
toc: true
sidebar:
  right:
    - toc
editor: source
---

Welcome to the **Innovating Science & Art Education**, where we combine place-based intertidal ecology education with open-source digital arts to foster learning, creativity, and community connection.


## About the Program

This pilot program is designed for high school students historically excluded from coastal environments. Our two-week curriculum is concentrated from the 5-week program we ran in Summer 2024 and features:\    
- Integration of science, digital storytelling, and cultural responsiveness.\    
- Building foundational intertidal ecology knowledge.\    
- Developing digital storytelling skills using open-source platforms like DaVinci Resolve and Echoes.\    

## What You’ll Find Here

Links to the content below can also be found in the header of each page.

- **[Schedule](schedule.qmd)**: A 2-week breakdown of the time blocks for each type of learning.
- **[Intertidal Lessons](lessons/intertidal_lesson1.qmd)**: Explore ecology topics.
- **[Art Lessons](lessons/art_lesson1.qmd)**: Dive into digital storytelling.
- **[Expansion Lessons](lessons/intertidal_scaling.qmd)**: Explore more advanced ecology topics.
- **[Community Builders](community_builders.qmd)**: Activities to foster connection.
- **[Resources](resources.qmd)**: A list of content to support our learning as educators and (soon to be) content experts.\  

We hope this program inspires curiosity and engagement with our amazing coastal ecosystems!
